name: jard
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.2 <3.0.0"

tags:
  - json
  - encode

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  args: ^2.4.1
